//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Maths.Graphs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Maths.Graphs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activities.
        /// </summary>
        internal static string Message_Activities {
            get {
                return ResourceManager.GetString("Message_Activities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string Message_Activity {
            get {
                return ResourceManager.GetString("Message_Activity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The computed schedule finish time ({0}) exceeds the maximum supported time value ({1}).
        /// </summary>
        internal static string Message_ComputedScheduleExceedsMaximumTimeValue {
            get {
                return ResourceManager.GetString("Message_ComputedScheduleExceedsMaximumTimeValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The number of {0} is {1}, which exceeds the maximum supported count of {2}.
        /// </summary>
        internal static string Message_CountExceedsMaximum {
            get {
                return ResourceManager.GetString("Message_CountExceedsMaximum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Values or counts outside the supported limits:.
        /// </summary>
        internal static string Message_LimitsExceeded {
            get {
                return ResourceManager.GetString("Message_LimitsExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to resources.
        /// </summary>
        internal static string Message_Resources {
            get {
                return ResourceManager.GetString("Message_Resources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}, which is outside the supported range of {2} to {3}.
        /// </summary>
        internal static string Message_ValueOutsideSupportedRange {
            get {
                return ResourceManager.GetString("Message_ValueOutsideSupportedRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to work streams.
        /// </summary>
        internal static string Message_WorkStreams {
            get {
                return ResourceManager.GetString("Message_WorkStreams", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All resources are explicit targets, but not all activities have targeted resources.
        /// </summary>
        internal static string Message_AllResourcesExplicitTargetsNotAllActivitiesTargeted {
            get {
                return ResourceManager.GetString("Message_AllResourcesExplicitTargetsNotAllActivitiesTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow graph state has no End node.
        /// </summary>
        internal static string Message_ArrowGraphStateHasNoEndNode {
            get {
                return ResourceManager.GetString("Message_ArrowGraphStateHasNoEndNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arrow graph state has no Start node.
        /// </summary>
        internal static string Message_ArrowGraphStateHasNoStartNode {
            get {
                return ResourceManager.GetString("Message_ArrowGraphStateHasNoStartNode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Distribution length ({0}) cannot be less than latest activity finish time ({1}).
        /// </summary>
        internal static string Message_DistributionLengthLessThanLatestActivityFinishTime {
            get {
                return ResourceManager.GetString("Message_DistributionLengthLessThanLatestActivityFinishTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Guid keys do not support Previous.
        /// </summary>
        internal static string Message_GuidKeysDoNotSupportPrevious {
            get {
                return ResourceManager.GetString("Message_GuidKeysDoNotSupportPrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keys for phase starting points does not match the keys for phase ending points for resource {0}.
        /// </summary>
        internal static string Message_PhaseStartKeysDoNotMatchPhaseEndKeys {
            get {
                return ResourceManager.GetString("Message_PhaseStartKeysDoNotMatchPhaseEndKeys", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scheduled activity's start time {0} is less than the earliest available start time for the next activity {1}.
        /// </summary>
        internal static string Message_ScheduledActivityStartTimeLessThanEarliestAvailableStartTime {
            get {
                return ResourceManager.GetString("Message_ScheduledActivityStartTimeLessThanEarliestAvailableStartTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supported for key generation.
        /// </summary>
        internal static string Message_TypeNotSupportedForKeyGeneration {
            get {
                return ResourceManager.GetString("Message_TypeNotSupportedForKeyGeneration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create a dummy activity assignable to type {0}.
        /// </summary>
        internal static string Message_UnableToCreateDummyActivityAssignableToType {
            get {
                return ResourceManager.GetString("Message_UnableToCreateDummyActivityAssignableToType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Arrow graph contains more than one End node.
        /// </summary>
        internal static string Message_ArrowGraphContainsMoreThanOneEndNode {
            get {
                return ResourceManager.GetString("Message_ArrowGraphContainsMoreThanOneEndNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow graph contains more than one Start node.
        /// </summary>
        internal static string Message_ArrowGraphContainsMoreThanOneStartNode {
            get {
                return ResourceManager.GetString("Message_ArrowGraphContainsMoreThanOneStartNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one activity requires a non-explicit target resource, but all provided resources are explicit targets.
        /// </summary>
        internal static string Message_AtLeastOneActivityRequiresNonExplicitTargetResourceButAllProvidedResourcesAreExplicitTargets {
            get {
                return ResourceManager.GetString("Message_AtLeastOneActivityRequiresNonExplicitTargetResourceButAllProvidedResource" +
                        "sAreExplicitTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of specified target resources are not available in the resources provided.
        /// </summary>
        internal static string Message_AtLeastOneOfSpecifiedTargetResourcesAreNotAvailableInResourcesProvided {
            get {
                return ResourceManager.GetString("Message_AtLeastOneOfSpecifiedTargetResourcesAreNotAvailableInResourcesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not be assigned to any resource.
        /// </summary>
        internal static string Message_CouldNotBeAssignedToAnyResource {
            get {
                return ResourceManager.GetString("Message_CouldNotBeAssignedToAnyResource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot backfill Isolated nodes.
        /// </summary>
        internal static string Message_CannotBackFillIsolatedNodes {
            get {
                return ResourceManager.GetString("Message_CannotBackFillIsolatedNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate critical path.
        /// </summary>
        internal static string Message_CannotCalculateCriticalPath {
            get {
                return ResourceManager.GetString("Message_CannotCalculateCriticalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate critical path backward flow.
        /// </summary>
        internal static string Message_CannotCalculateCriticalPathBackwardFlow {
            get {
                return ResourceManager.GetString("Message_CannotCalculateCriticalPathBackwardFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate critical path forward flow.
        /// </summary>
        internal static string Message_CannotCalculateCriticalPathForwardFlow {
            get {
                return ResourceManager.GetString("Message_CannotCalculateCriticalPathForwardFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate critical path priority list.
        /// </summary>
        internal static string Message_CannotCalculateCriticalPathPriorityList {
            get {
                return ResourceManager.GetString("Message_CannotCalculateCriticalPathPriorityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate earliest finish times due to cyclic dependency.
        /// </summary>
        internal static string Message_CannotCalculateEarliestFinishTimesDueToCyclicDependency {
            get {
                return ResourceManager.GetString("Message_CannotCalculateEarliestFinishTimesDueToCyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate Event earliest finish times.
        /// </summary>
        internal static string Message_CannotCalculateEventEarliestFinishTimes {
            get {
                return ResourceManager.GetString("Message_CannotCalculateEventEarliestFinishTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate Event latest finish times.
        /// </summary>
        internal static string Message_CannotCalculateEventLatestFinishTimes {
            get {
                return ResourceManager.GetString("Message_CannotCalculateEventLatestFinishTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate latest finish times due to cyclic dependency.
        /// </summary>
        internal static string Message_CannotCalculateLatestFinishTimesDueToCyclicDependency {
            get {
                return ResourceManager.GetString("Message_CannotCalculateLatestFinishTimesDueToCyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct arrow graph due to invalid dependencies.
        /// </summary>
        internal static string Message_CannotConstructArrowGraphDueToInvalidDependencies {
            get {
                return ResourceManager.GetString("Message_CannotConstructArrowGraphDueToInvalidDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform edge redirection.
        /// </summary>
        internal static string Message_CannotPerformEdgeRedirection {
            get {
                return ResourceManager.GetString("Message_CannotPerformEdgeRedirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform transitive reduction.
        /// </summary>
        internal static string Message_CannotPerformTransitiveReduction {
            get {
                return ResourceManager.GetString("Message_CannotPerformTransitiveReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove redundant edges.
        /// </summary>
        internal static string Message_CannotRemoveRedundantEdges {
            get {
                return ResourceManager.GetString("Message_CannotRemoveRedundantEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set MinimumFreeSlack and MaximumLatestFinishTime at the same time.
        /// </summary>
        internal static string Message_CannotSetMinimumFreeSlackAndMaximumLatestFinishTime {
            get {
                return ResourceManager.GetString("Message_CannotSetMinimumFreeSlackAndMaximumLatestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular activity dependencies:.
        /// </summary>
        internal static string Message_CircularDependencies {
            get {
                return ResourceManager.GetString("Message_CircularDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarliestFinishTime cannot be less than zero.
        /// </summary>
        internal static string Message_EarliestFinishTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_EarliestFinishTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarliestStartTime cannot be less than MinimumEarliestStartTime.
        /// </summary>
        internal static string Message_EarliestStartTimeLessThanMinimumEarliestStartTime {
            get {
                return ResourceManager.GetString("Message_EarliestStartTimeLessThanMinimumEarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarliestStartTime cannot be less than zero.
        /// </summary>
        internal static string Message_EarliestStartTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_EarliestStartTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeSlack cannot be less than MinimumFreeSlack.
        /// </summary>
        internal static string Message_FreeSlackLessThanMinimumFreeSlack {
            get {
                return ResourceManager.GetString("Message_FreeSlackLessThanMinimumFreeSlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internally inconsistent input collections (possible concurrent modification of compilation inputs):.
        /// </summary>
        internal static string Message_InternallyInconsistentCollections {
            get {
                return ResourceManager.GetString("Message_InternallyInconsistentCollections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid activity constraints:.
        /// </summary>
        internal static string Message_InvalidConstraints {
            get {
                return ResourceManager.GetString("Message_InvalidConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid activity dependencies:.
        /// </summary>
        internal static string Message_InvalidDependencies {
            get {
                return ResourceManager.GetString("Message_InvalidDependencies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to none of its target resources are available:.
        /// </summary>
        internal static string Message_NoneOfTargetResourcesAreAvailable {
            get {
                return ResourceManager.GetString("Message_NoneOfTargetResourcesAreAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to has no target resources, but every supplied resource is an explicit target.
        /// </summary>
        internal static string Message_NoTargetResourcesButAllResourcesAreExplicitTargets {
            get {
                return ResourceManager.GetString("Message_NoTargetResourcesButAllResourcesAreExplicitTargets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string Message_Resource {
            get {
                return ResourceManager.GetString("Message_Resource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to requires all of its target resources, but the following are not available:.
        /// </summary>
        internal static string Message_RequiresAllTargetResourcesButSomeNotAvailable {
            get {
                return ResourceManager.GetString("Message_RequiresAllTargetResourcesButSomeNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cannot be scheduled within the maximum supported time value ({0}).
        /// </summary>
        internal static string Message_CannotBeScheduledWithinMaximumTimeValue {
            get {
                return ResourceManager.GetString("Message_CannotBeScheduledWithinMaximumTimeValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to its target resource set is internally inconsistent - lookups disagree with its contents (possible concurrent modification of compilation inputs).
        /// </summary>
        internal static string Message_TargetResourceSetInternallyInconsistent {
            get {
                return ResourceManager.GetString("Message_TargetResourceSetInternallyInconsistent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to waiting on dependencies that can never complete:.
        /// </summary>
        internal static string Message_WaitingOnDependenciesThatCanNeverComplete {
            get {
                return ResourceManager.GetString("Message_WaitingOnDependenciesThatCanNeverComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is invalid but referenced by:.
        /// </summary>
        internal static string Message_IsInvalidButReferencedBy {
            get {
                return ResourceManager.GetString("Message_IsInvalidButReferencedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestFinishTime cannot be less than EarliestFinishTime.
        /// </summary>
        internal static string Message_LatestFinishTimeLessThanEarliestFinishTime {
            get {
                return ResourceManager.GetString("Message_LatestFinishTimeLessThanEarliestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestFinishTime cannot be less than zero.
        /// </summary>
        internal static string Message_LatestFinishTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_LatestFinishTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestFinishTime cannot be more than MaximumLatestFinishTime.
        /// </summary>
        internal static string Message_LatestFinishTimeMoreThanMaximumLatestFinishTime {
            get {
                return ResourceManager.GetString("Message_LatestFinishTimeMoreThanMaximumLatestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestStartTime cannot be less than EarliestStartTime.
        /// </summary>
        internal static string Message_LatestStartTimeLessThanEarliestStartTime {
            get {
                return ResourceManager.GetString("Message_LatestStartTimeLessThanEarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestStartTime cannot be less than zero.
        /// </summary>
        internal static string Message_LatestStartTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_LatestStartTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by head Nodes do not match.
        /// </summary>
        internal static string Message_ListOfEdgeIdsAndEdgesReferencedByHeadNodesDoNotMatch {
            get {
                return ResourceManager.GetString("Message_ListOfEdgeIdsAndEdgesReferencedByHeadNodesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by tail Nodes do not match.
        /// </summary>
        internal static string Message_ListOfEdgeIdsAndEdgesReferencedByTailNodesDoNotMatch {
            get {
                return ResourceManager.GetString("Message_ListOfEdgeIdsAndEdgesReferencedByTailNodesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Node IDs and Edges referenced by tail Nodes do not match.
        /// </summary>
        internal static string Message_ListOfNodeIdsAndEdgesReferencedByTailNodesDoNotMatch {
            get {
                return ResourceManager.GetString("Message_ListOfNodeIdsAndEdgesReferencedByTailNodesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (MinimumEarliestStartTime + Duration) must be greater than MaximumLatestFinishTime.
        /// </summary>
        internal static string Message_MinimumEarliestStartTimePlusDurationMustBeGreaterThanMaximumLatestFinishTime {
            get {
                return ResourceManager.GetString("Message_MinimumEarliestStartTimePlusDurationMustBeGreaterThanMaximumLatestFinishT" +
                        "ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource scheduling could not make progress with the following activities:.
        /// </summary>
        internal static string Message_ResourceSchedulingStalled {
            get {
                return ResourceManager.GetString("Message_ResourceSchedulingStalled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to remove unnecessary edges.
        /// </summary>
        internal static string Message_UnableToRemoveUnnecessaryEdges {
            get {
                return ResourceManager.GetString("Message_UnableToRemoveUnnecessaryEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable resources for activities:.
        /// </summary>
        internal static string Message_UnavailableResources {
            get {
                return ResourceManager.GetString("Message_UnavailableResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be negative.
        /// </summary>
        internal static string Message_ValueCannotBeNegative {
            get {
                return ResourceManager.GetString("Message_ValueCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex graph cannot contain Normal nodes without any End nodes.
        /// </summary>
        internal static string Message_VertexGraphCannotContainNormalNodesWithoutAnyEndNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphCannotContainNormalNodesWithoutAnyEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex graph cannot contain Normal nodes without any Start nodes.
        /// </summary>
        internal static string Message_VertexGraphCannotContainNormalNodesWithoutAnyStartNodes {
            get {
                return ResourceManager.GetString("Message_VertexGraphCannotContainNormalNodesWithoutAnyStartNodes", resourceCulture);
            }
        }
    }
}
