//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Maths.Graphs.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Maths.Graphs.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow graph contains more than one End node.
        /// </summary>
        internal static string ArrowGraphContainsMoreThanOneEndNode {
            get {
                return ResourceManager.GetString("ArrowGraphContainsMoreThanOneEndNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow graph contains more than one Start node.
        /// </summary>
        internal static string ArrowGraphContainsMoreThanOneStartNode {
            get {
                return ResourceManager.GetString("ArrowGraphContainsMoreThanOneStartNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one activity requires a non-explicit target resource, but all provided resources are explicit targets.
        /// </summary>
        internal static string AtLeastOneActivityRequiresNonExplicitTargetResourceButAllProvidedResourcesAreExplicitTargets {
            get {
                return ResourceManager.GetString("AtLeastOneActivityRequiresNonExplicitTargetResourceButAllProvidedResourcesAreExpl" +
                        "icitTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one specified target resources are not present in the resources provided.
        /// </summary>
        internal static string AtLeastOneSpecifiedTargetResourcesAreNotPresentInResourcesProvided {
            get {
                return ResourceManager.GetString("AtLeastOneSpecifiedTargetResourcesAreNotPresentInResourcesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate critical path.
        /// </summary>
        internal static string CannotCalculateCriticalPath {
            get {
                return ResourceManager.GetString("CannotCalculateCriticalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate critical path backward flow.
        /// </summary>
        internal static string CannotCalculateCriticalPathBackwardFlow {
            get {
                return ResourceManager.GetString("CannotCalculateCriticalPathBackwardFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate critical path forward flow.
        /// </summary>
        internal static string CannotCalculateCriticalPathForwardFlow {
            get {
                return ResourceManager.GetString("CannotCalculateCriticalPathForwardFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate critical path priority list.
        /// </summary>
        internal static string CannotCalculateCriticalPathPriorityList {
            get {
                return ResourceManager.GetString("CannotCalculateCriticalPathPriorityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate earliest finish times due to cyclic dependency.
        /// </summary>
        internal static string CannotCalculateEarliestFinishTimesDueToCyclicDependency {
            get {
                return ResourceManager.GetString("CannotCalculateEarliestFinishTimesDueToCyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate Event earliest finish times.
        /// </summary>
        internal static string CannotCalculateEventEarliestFinishTimes {
            get {
                return ResourceManager.GetString("CannotCalculateEventEarliestFinishTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate Event latest finish times.
        /// </summary>
        internal static string CannotCalculateEventLatestFinishTimes {
            get {
                return ResourceManager.GetString("CannotCalculateEventLatestFinishTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate latest finish times due to cyclic dependency.
        /// </summary>
        internal static string CannotCalculateLatestFinishTimesDueToCyclicDependency {
            get {
                return ResourceManager.GetString("CannotCalculateLatestFinishTimesDueToCyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct arrow graph due to missing dependencies.
        /// </summary>
        internal static string CannotConstructArrowGraphDueToMissingDependencies {
            get {
                return ResourceManager.GetString("CannotConstructArrowGraphDueToMissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform edge clean up.
        /// </summary>
        internal static string CannotPerformEdgeCleanUp {
            get {
                return ResourceManager.GetString("CannotPerformEdgeCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform transitive reduction.
        /// </summary>
        internal static string CannotPerformTransitiveReduction {
            get {
                return ResourceManager.GetString("CannotPerformTransitiveReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by head Nodes do not match.
        /// </summary>
        internal static string ListOfEdgeIdsAndEdgesReferencedByHeadNodesDoNotMatch {
            get {
                return ResourceManager.GetString("ListOfEdgeIdsAndEdgesReferencedByHeadNodesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Edge IDs and Edges referenced by tail Nodes do not match.
        /// </summary>
        internal static string ListOfEdgeIdsAndEdgesReferencedByTailNodesDoNotMatch {
            get {
                return ResourceManager.GetString("ListOfEdgeIdsAndEdgesReferencedByTailNodesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Node IDs and Edges referenced by tail Nodes do not match.
        /// </summary>
        internal static string ListOfNodeIdsAndEdgesReferencedByTailNodesDoNotMatch {
            get {
                return ResourceManager.GetString("ListOfNodeIdsAndEdgesReferencedByTailNodesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All resources are explicit targets, but not all activities have targeted resources.
        /// </summary>
        internal static string Message_AllResourcesExplicitTargetsNotAllActivitiesTargeted {
            get {
                return ResourceManager.GetString("Message_AllResourcesExplicitTargetsNotAllActivitiesTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set MinimumFreeSlack and MaximumLatestFinishTime at the same time.
        /// </summary>
        internal static string Message_CannotSetMinimumFreeSlackAndMaximumLatestFinishTime {
            get {
                return ResourceManager.GetString("Message_CannotSetMinimumFreeSlackAndMaximumLatestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular activity dependencies:.
        /// </summary>
        internal static string Message_CircularDependencies {
            get {
                return ResourceManager.GetString("Message_CircularDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarliestFinishTime cannot be less than zero.
        /// </summary>
        internal static string Message_EarliestFinishTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_EarliestFinishTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarliestStartTime cannot be less than zero.
        /// </summary>
        internal static string Message_EarliestStartTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_EarliestStartTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid activity constraints:.
        /// </summary>
        internal static string Message_InvalidConstraints {
            get {
                return ResourceManager.GetString("Message_InvalidConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is missing from:.
        /// </summary>
        internal static string Message_IsMissingFrom {
            get {
                return ResourceManager.GetString("Message_IsMissingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestFinishTime cannot be less than EarliestFinishTime.
        /// </summary>
        internal static string Message_LatestFinishTimeLessThanEarliestFinishTime {
            get {
                return ResourceManager.GetString("Message_LatestFinishTimeLessThanEarliestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestFinishTime cannot be less than zero.
        /// </summary>
        internal static string Message_LatestFinishTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_LatestFinishTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestStartTime cannot be less than EarliestStartTime.
        /// </summary>
        internal static string Message_LatestStartTimeLessThanEarliestStartTime {
            get {
                return ResourceManager.GetString("Message_LatestStartTimeLessThanEarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestStartTime cannot be less than zero.
        /// </summary>
        internal static string Message_LatestStartTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_LatestStartTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (MinimumEarliestStartTime + Duration) must be greater than MaximumLatestFinishTime.
        /// </summary>
        internal static string Message_MinimumEarliestStartTimePlusDurationMustBeGreaterThanMaximumLatestFinishTime {
            get {
                return ResourceManager.GetString("Message_MinimumEarliestStartTimePlusDurationMustBeGreaterThanMaximumLatestFinishT" +
                        "ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing activity dependencies:.
        /// </summary>
        internal static string Message_MissingDependencies {
            get {
                return ResourceManager.GetString("Message_MissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove unnecessary edges.
        /// </summary>
        internal static string Message_UnableToRemoveUnnecessaryEdges {
            get {
                return ResourceManager.GetString("Message_UnableToRemoveUnnecessaryEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable resources for activities:.
        /// </summary>
        internal static string Message_UnavailableResources {
            get {
                return ResourceManager.GetString("Message_UnavailableResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be negative.
        /// </summary>
        internal static string ValueCannotBeNegative {
            get {
                return ResourceManager.GetString("ValueCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex graph cannot contain Normal nodes without any End nodes.
        /// </summary>
        internal static string VertexGraphCannotContainNormalNodesWithoutAnyEndNodes {
            get {
                return ResourceManager.GetString("VertexGraphCannotContainNormalNodesWithoutAnyEndNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex graph cannot contain Normal nodes without any Start nodes.
        /// </summary>
        internal static string VertexGraphCannotContainNormalNodesWithoutAnyStartNodes {
            get {
                return ResourceManager.GetString("VertexGraphCannotContainNormalNodesWithoutAnyStartNodes", resourceCulture);
            }
        }
    }
}
