//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Maths.Graphs {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Maths.Graphs.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All resources are explicit targets, but not all activities have targeted resources.
        /// </summary>
        internal static string Message_AllResourcesExplicitTargetsNotAllActivitiesTargeted {
            get {
                return ResourceManager.GetString("Message_AllResourcesExplicitTargetsNotAllActivitiesTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set MinimumFreeSlack and MaximumLatestFinishTime at the same time.
        /// </summary>
        internal static string Message_CannotSetMinimumFreeSlackAndMaximumLatestFinishTime {
            get {
                return ResourceManager.GetString("Message_CannotSetMinimumFreeSlackAndMaximumLatestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular activity dependencies:.
        /// </summary>
        internal static string Message_CircularDependencies {
            get {
                return ResourceManager.GetString("Message_CircularDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarliestFinishTime cannot be less than zero.
        /// </summary>
        internal static string Message_EarliestFinishTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_EarliestFinishTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarliestStartTime cannot be less than zero.
        /// </summary>
        internal static string Message_EarliestStartTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_EarliestStartTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid activity constraints:.
        /// </summary>
        internal static string Message_InvalidConstraints {
            get {
                return ResourceManager.GetString("Message_InvalidConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is missing from:.
        /// </summary>
        internal static string Message_IsMissingFrom {
            get {
                return ResourceManager.GetString("Message_IsMissingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestFinishTime cannot be less than EarliestFinishTime.
        /// </summary>
        internal static string Message_LatestFinishTimeLessThanEarliestFinishTime {
            get {
                return ResourceManager.GetString("Message_LatestFinishTimeLessThanEarliestFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestFinishTime cannot be less than zero.
        /// </summary>
        internal static string Message_LatestFinishTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_LatestFinishTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestStartTime cannot be less than EarliestStartTime.
        /// </summary>
        internal static string Message_LatestStartTimeLessThanEarliestStartTime {
            get {
                return ResourceManager.GetString("Message_LatestStartTimeLessThanEarliestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestStartTime cannot be less than zero.
        /// </summary>
        internal static string Message_LatestStartTimeLessThanZero {
            get {
                return ResourceManager.GetString("Message_LatestStartTimeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (MinimumEarliestStartTime + Duration) must be greater than MaximumLatestFinishTime.
        /// </summary>
        internal static string Message_MinimumEarliestStartTimePlusDurationMustBeGreaterThanMaximumLatestFinishTime {
            get {
                return ResourceManager.GetString("Message_MinimumEarliestStartTimePlusDurationMustBeGreaterThanMaximumLatestFinishT" +
                        "ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing activity dependencies:.
        /// </summary>
        internal static string Message_MissingDependencies {
            get {
                return ResourceManager.GetString("Message_MissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove unnecessary edges.
        /// </summary>
        internal static string Message_UnableToRemoveUnnecessaryEdges {
            get {
                return ResourceManager.GetString("Message_UnableToRemoveUnnecessaryEdges", resourceCulture);
            }
        }
    }
}
